---
vas:
  hci:
    stages:
      - path: examples/va/hci/control-plane/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/hci/control-plane
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=30m
        values:
          - name: network-values
            src_file: nncp/values.yaml
        build_output: ../control-plane.yaml

      - path: examples/va/hci/edpm-pre-ceph
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment-pre-ceph --for condition=Ready
            --timeout=1500s
        values:
          - name: edpm-nodeset-values
            src_file: nodeset-values.yaml
          - name: edpm-deployment-values
            src_file: deployment-values.yaml
        build_output: dataplane-pre-ceph.yaml
        post_stage_run:
          - name: Deploy Ceph
            type: playbook
            source: "../../playbooks/ceph.yml"
            inventory: "${HOME}/ci-framework-data/artifacts/zuul_inventory.yml"

      - path: examples/va/hci
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment-post-ceph --for condition=Ready
            --timeout=40m
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: edpm-nodeset-values-post-ceph
            src_file: nodeset-values.yaml
          - name: edpm-deployment-values-post-ceph
            src_file: deployment-values.yaml
        build_output: dataplane-post-ceph.yaml

  sriov:
    stages:
      - path: examples/va/nfv/sriov/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/sriov
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/sriov/edpm
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment --for condition=Ready --timeout=1200s
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: dataplane.yaml

  ovs-dpdk:
    stages:
      - path: examples/va/nfv/ovs-dpdk/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/ovs-dpdk
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/ovs-dpdk/edpm
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment --for condition=Ready --timeout=1200s
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: dataplane.yaml

  ovs-dpdk-sriov:
    stages:
      - path: examples/va/nfv/ovs-dpdk-sriov/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/ovs-dpdk-sriov
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/ovs-dpdk-sriov/edpm
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment --for condition=Ready --timeout=1200s
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: dataplane.yaml

  uni06zeta:
    stages:
      - path: examples/dt/uni06zeta/control-plane/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s

        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/dt/uni06zeta/control-plane
        wait_conditions:
          - >-
            oc -n openstack wait openstackcontrolplane
            controlplane
            --for condition=Ready
            --timeout=600s

        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/dt/uni06zeta
        wait_conditions:
          - >-
            oc -n openstack wait openstackdataplanedeployment
            edpm-deployment
            --for condition=Ready
            --timeout=1200s
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: edpm.yaml
